[package]
name = "ashv"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
winit = "0.30.12"
